### ISSUE TITLE
Training Error ：ModuleNotFoundError: No module named 'bevdepth'

### ISSUE THREAD

**Issue by stduent-vehicle** [sanmin0312/LabelDistill#1]
(labeldistill) aistudio@jupyter-89601-8417844:~/LabelDistill$ python labeldistill/exps/nuscenes/labeldistill/centerpoint_vox01_128x128_20e_10sweeps.py --amp_backend native -b 4 
Traceback (most recent call last):
  File "labeldistill/exps/nuscenes/labeldistill/centerpoint_vox01_128x128_20e_10sweeps.py", line 5, in <module>
    from bevdepth.exps.base_cli import run_cli
ModuleNotFoundError: No module named 'bevdepth'

**Comment by sanmin0312** [comment]
The config file 'centerpoint_vox01_128x128_20e_10sweeps.py' was uploaded prematurely and still requires significant modifications. Unfortunately, due to my current workload, I won't be able to make the necessary updates right away, but I will fix it as soon as possible.

In the meantime, if you're working with the teacher model, you can use the pre-trained CenterPoint (LiDAR Teacher) model provided in the Model Zoo, which does not require training.
